### 빈 쿼리 전송
GET http://localhost:8080/v1/place?q=


### 카카오 5, 네이버 5, 중복 3
GET http://localhost:8080/v1/place?q=국민은행 여의도

### 카카오 1, 네이버 3, 중복 1
GET http://localhost:8080/v1/place?q=밤비노아울렛

### 카카오 5, 네이버 4, 중복 1 (카카오 추가 요청으로 카카오 제공 데이터 6개)
GET http://localhost:8080/v1/place?q=양양 양고기

### 카카오 1, 네이버 5, 중복 1 (네이버 추가 요청으로 네이버 제공 데이터 9개)
GET http://localhost:8080/v1/place?q=안동 바버샵

### 인기 검색어 TOP 10, 비동기로 카운팅되고 있어요. (동기화 간격: 10s)
GET http://localhost:8080/v1/place/queries/top10
